export { default as Seo } from "./seo"
export { default as About } from "./about"
export { default as Overview } from "./overview"
export { default as Testimonials } from "./testimonials"
export { default as Featured } from "./featured"
export { default as Blog } from "./blog"